# Generated by Django 4.2.4 on 2023-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name')),
                ('password', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone_number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='client_user/', verbose_name='profile_image')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='language')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is_anonymous')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superadmin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
