# Generated by Django 4.2.4 on 2023-08-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_language_account_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='remember_me',
        ),
    ]
