# Generated by Django 4.2.4 on 2023-08-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_visa_user'),
        ('accounts', '0004_remove_account_remember_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_owner', to='property.visa'),
        ),
    ]
