# Generated by Django 4.2.4 on 2023-08-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_visa_user_visa_email_visa_phone_number_and_more'),
        ('accounts', '0006_remove_account_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_owner', to='property.visa'),
        ),
    ]
