# Generated by Django 4.2.4 on 2023-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('fd_link', models.URLField(max_length=300)),
                ('twitter_link', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
            ],
        ),
    ]
