# Generated by Django 4.2.4 on 2023-09-18 18:55

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='logo')),
                ('fb_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='fb_link')),
                ('twitter_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='twitter_link')),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='instagram_link')),
                ('linkedin_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='linkedin_link')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('site_header', models.CharField(db_index=True, max_length=50, verbose_name='site_header')),
                ('phone', models.CharField(db_index=True, max_length=40, verbose_name='phone')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='email')),
                ('description', models.TextField(db_index=True, max_length=300, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.settings')),
            ],
            options={
                'verbose_name': 'settings Translation',
                'db_table': 'settings_settings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
