# Generated by Django 4.2.4 on 2023-09-18 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='number_phone')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='place')),
                ('check_in', models.DateField(default=django.utils.timezone.now, verbose_name='check_in')),
                ('check_out', models.DateField(default=django.utils.timezone.now, verbose_name='check_out')),
                ('adults_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='adults_number')),
                ('children_number_and_their_age', models.TextField(blank=True, max_length=1000, null=True, verbose_name='children_number_and_their_age')),
                ('infant', models.CharField(blank=True, max_length=1000, null=True, verbose_name='infant')),
                ('room_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='room_number')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='notes')),
                ('consultant_request', models.CharField(default=True, verbose_name='consultant_request')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='number_phone')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='place')),
                ('check_in', models.DateField(default=django.utils.timezone.now, verbose_name='check_in')),
                ('check_out', models.DateField(default=django.utils.timezone.now, verbose_name='check_out')),
                ('adults_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='adults_number')),
                ('children_number_and_their_age', models.TextField(blank=True, max_length=1000, null=True, verbose_name='children_number_and_their_age')),
                ('infant', models.TextField(blank=True, max_length=1000, null=True, verbose_name='infant')),
                ('room_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='room_number')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='notes')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(db_index=True, max_length=150, null=True, verbose_name='question')),
                ('answer', models.TextField(db_index=True, max_length=3000, null=True, verbose_name='answer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.faq')),
            ],
            options={
                'verbose_name': 'faq Translation',
                'db_table': 'about_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('who_we_are', models.TextField(db_index=True, max_length=1000, verbose_name='who_we_are')),
                ('what_we_do', models.TextField(db_index=True, max_length=1000, verbose_name='what_we_do')),
                ('our_mission', models.TextField(db_index=True, max_length=1000, verbose_name='our_mission')),
                ('our_goals', models.TextField(db_index=True, max_length=1000, verbose_name='our_goals')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.about')),
            ],
            options={
                'verbose_name': 'about Translation',
                'db_table': 'about_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
