# Generated by Django 4.2.4 on 2023-09-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property/', verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('number_of_guests', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='number_of_guests')),
                ('number_of_rooms', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='number_of_rooms')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='duration')),
                ('price_per_child', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_per_child')),
                ('check_in', models.DateField(null=True, verbose_name='check_in')),
                ('check_out', models.DateField(null=True, verbose_name='check_out')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category', verbose_name='category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='property.place', verbose_name='place')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='number_phone')),
                ('visa', models.FileField(blank=True, null=True, upload_to='visas/', verbose_name='visa')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personal_photos/', verbose_name='photo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_owner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='rate')),
                ('feedback', models.TextField(blank=True, max_length=2000, null=True, verbose_name='feedback')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_auther', to=settings.AUTH_USER_MODEL, verbose_name='auther')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_trip', to='property.trip', verbose_name='trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_images/', verbose_name='image')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TripGallery_images', to='property.trip', verbose_name='trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='check_out')),
                ('guest', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='guest')),
                ('children', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='children')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_trip', to='property.trip', verbose_name='trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAvailabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='lastname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('number_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='number_phone')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='place')),
                ('check_in', models.DateField(default=django.utils.timezone.now, verbose_name='check_in')),
                ('check_out', models.DateField(default=django.utils.timezone.now, verbose_name='check_out')),
                ('adults_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='adults_number')),
                ('children_number_and_their_age', models.TextField(blank=True, max_length=1000, null=True, verbose_name='children_number_and_their_age')),
                ('infant', models.TextField(blank=True, max_length=1000, null=True, verbose_name='infant')),
                ('room_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='room_number')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_owner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='TripTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('stars', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='stars')),
                ('price_of_single_room_by_person_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_single_room_by_person_night')),
                ('price_of_double_room_by_person_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_double_room_by_person_night')),
                ('price_of_triple_room_by_person_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_triple_room_by_person_night')),
                ('price_of_single_room_by_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_single_room_by_night')),
                ('price_of_double_room_by_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_double_room_by_night')),
                ('price_of_triple_room_by_night', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='price_of_triple_room_by_night')),
                ('description', models.TextField(db_index=True, max_length=10000, verbose_name='description')),
                ('slug', models.CharField(blank=True, db_index=True, null=True, unique=True, verbose_name='slug')),
                ('trip_summary', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='trip_summary')),
                ('accommodation', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='accommodation')),
                ('includes_and_excludes', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='includes_and_excludes')),
                ('itinerary', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='itinerary')),
                ('cancellation_policy', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='cancellation_policy')),
                ('terms_conditions', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='terms_conditions')),
                ('notes', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='notes')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='property.trip')),
            ],
            options={
                'verbose_name': 'trip Translation',
                'db_table': 'property_trip_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='property.place')),
            ],
            options={
                'verbose_name': 'place Translation',
                'db_table': 'property_place_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='property.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'property_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
