# Generated by Django 4.2.4 on 2023-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_double_room_by_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_double_room_by_person_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_single_room_by_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_single_room_by_person_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_triple_room_by_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='price_of_triple_room_by_person_night',
        ),
        migrations.RemoveField(
            model_name='triptranslation',
            name='stars',
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_double_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_double_room_by_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_double_room_by_person_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_double_room_by_person_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_single_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_single_room_by_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_single_room_by_person_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_single_room_by_person_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_triple_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_triple_room_by_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_of_triple_room_by_person_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='price_of_triple_room_by_person_night'),
        ),
        migrations.AddField(
            model_name='trip',
            name='stars',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='stars'),
        ),
    ]
