# Generated by Django 4.2.4 on 2023-08-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_by_night',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_by_person',
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_double_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_double_room_by_person',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_single_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_single_room_by_person',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_triple_room_by_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_of_triple_room_by_person',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
