# Generated by Django 4.2.4 on 2023-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_price_remove_property_price_by_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
