# Generated by Django 4.2.4 on 2023-09-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name_plural': 'Reservations'},
        ),
    ]
