# Generated by Django 4.2.4 on 2023-09-25 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_reservations_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='check_out',
        ),
        migrations.AddField(
            model_name='reservations',
            name='children_number_and_their_age',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservations',
            name='guest_number_and_their_name_email_and_their_phone_number',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='infant',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='notes',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
