# Generated by Django 4.2.4 on 2023-08-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyavailabilitycheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyavailabilitycheck',
            name='user',
        ),
        migrations.AddField(
            model_name='propertyavailabilitycheck',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertyavailabilitycheck',
            name='number_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
