# Generated by Django 4.2.4 on 2023-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_reservations_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='guest_number_and_their_name_email_and_their_phone_number',
            new_name='guests_info',
        ),
        migrations.AddField(
            model_name='reservations',
            name='adult_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
