# Generated by Django 4.2.4 on 2023-08-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_propertyavailabilitycheck_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyavailabilitycheck',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
