# Generated by Django 4.2.4 on 2023-09-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_reservations_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_trips', to='property.trip', unique=True),
        ),
    ]
