# Generated by Django 4.2.4 on 2023-08-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertyavailabilitycheck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='user',
        ),
    ]
