# Generated by Django 4.2.4 on 2023-08-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_visa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='personal_photo',
            new_name='photo',
        ),
    ]
