# Generated by Django 4.2.4 on 2023-08-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_rename_personal_photo_visa_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_visa', to=settings.AUTH_USER_MODEL),
        ),
    ]
