# Generated by Django 4.2.4 on 2023-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_visa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='user',
        ),
        migrations.AddField(
            model_name='visa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
