# Generated by Django 4.2.4 on 2023-10-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_reservations_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreview',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_trip', to='property.trip', verbose_name='trip'),
        ),
    ]
