# Generated by Django 4.2.4 on 2023-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_tripreview_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreview',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='rate'),
        ),
    ]
