# Generated by Django 4.2.4 on 2023-10-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_delete_tripbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='property.trip'),
        ),
    ]
